version: '3'
services:
  jupyter:
    image: jupyter/scipy-notebook
    container_name: jupyter
    environment:
      - SQL_HOST=실서버 DB 주소
      - SQL_USER=실서버 DB 유저
      - SQL_PASSWORD=실서버 DB 비밀번호
      - DATABASE=실서버 DB 이름
      - AWS_ACCESS_KEY_ID=실서버 AWS ACCESS KEY
      - AWS_SECRET_ACCESS_KEY=실서버 AWS SECRET ACCESS KEY
      - NODE_SERVER=실서버 NODE 서버 주소
    ports:
      - "8888:8888"
    volumes:
      - ./jupyter:/home/jovyan
      - ./config.py:/home/libs/config.py
    user: root
    command: >
      sh -c '
        pip install awscli requests && \
        pip install --no-cache-dir sqlalchemy ipython-sql mysql-connector-python  && \
        start.sh jupyter lab --NotebookApp.token="conf" --ip="0.0.0.0" --port=8888
      '